### ISSUE TITLE
GCIS namespace declarations

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis-ontology#86]
With regard to the namespace declarations at the end of the document accessible at:
http://data.globalchange.gov/gcis.owl (last accessed today)

a couple of things stand out.

Notably, do we have a namespace called "data-globalchange-gov" or should this just be called "gcis?"  If so, is there a need for this in addition to the "default namespace?"  Is the "skos2" namespace meant to just be "skos?"  Also, we use "dcterms" in-lieu of "terms" in various turtle templates, and the "dbpedia" namespace is identified as "property."

Also, various domain and ranges hyperlinks from the "data properties" section on are not clickable, although the URLs are present when hovering over them with a mouse.  Is this purposeful?  I'm using Chrome.

Or, am I just completely missing something, in which case we should discuss by phone first.  Thanks.

**Comment by zednis** [comment]
1) I lowered the priority because this is just documentation.

2) The namespace prefix used is not that critical as long as the computed URI is correct. e.g. using "dct" or "dcterms" for dublin core terms doesn't matter from a technical perspective.

3) The namespace used in the current gcis.ttl in this repository is `gcis`.

```
@prefix gcis: <http://data.globalchange.gov/gcis.owl#> .
```

4) The namespace prefixes used in the documentation do not match those in gcis.ttl.  Either LODE is generating its own namespace prefixes or this documentation is based off an a very old version of the ontology with different namespace prefixes.  Either way we should develop a process to regularly generate and deploy new documentation based on the current ontology (see #16 for related) and we can make sure to address any namespace prefix issues during that process.

5) The links in the documentation are for properties, classes, and instances defined in the GCIS ontology document.  In the case were the property referenced does not have a local definition (say from PROV, DCT, etc) there is not going to be a link to the definition of the property or class in the HTML.

**Comment by xgmachina** [comment]
And, check the prefix.cc site page: http://prefix.cc/gcis

**Comment by justgo129** [comment]
@rewolfe I'll defer this your way.

**Comment by justgo129** [comment]
@zednis @xgmachina @bduggan given the comment of @zednis above coupled with that #16 is now resolved, is there any action to be taken on #86 or would this be an example of "close with no action taken?"  Thanks.

**Comment by justgo129** [comment]
Closed #86 with no action taken.  Please don't hesitate to reopen if deemed appropriate.
